# Read the Docs

version: 2

formats:
  - htmlzip
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

build:
  os: ubuntu-22.04
  tools:
    python: '3.10'

sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: false
