name: MATLAB test multi-OS

on:
  push:
    branches: [main, matlab]

jobs:

  test:

    name: MATLAB ${{ matrix.matlab }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        matlab: [R2022a, R2023a, R2024a]

    steps:

      - name: Check out repository (branch main) with submodules
        uses: actions/checkout@v4
        with:
          ref: matlab
          submodules: recursive

      - name: Set up MATLAB with optimization toolbox and parallel computing toolbox
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab }}
          cache: true
          products: Optimization_Toolbox Parallel_Computing_Toolbox

      - name: Setup OptiProfiler and run tests
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            root_dir = pwd()

            % Setup OptiProfiler
            setup

            % Create a directory for the output
            mkdir('output')
            cd output

            % Test installation
            testOptiProfiler

            % Add './matlab/optiprofiler/tests/action_tests' to the path
            addpath(fullfile(root_dir, 'matlab/optiprofiler/tests/action_tests'))

            % Generate the benchmark_id with operating system and MATLAB version
            os = computer('arch');
            matlab_version = version('-release');
            benchmark_id = ['os_', os, '_matlab_', matlab_version];

            % Run the action tests
            tic
            test_plain(benchmark_id)
            fprintf('Time for plain test: %.2f seconds\n', toc);
            tic
            test_perturbed_x0(benchmark_id)
            fprintf('Time for perturbed_x0 test: %.2f seconds\n', toc);
            tic
            test_noisy(benchmark_id)
            fprintf('Time for noisy test: %.2f seconds\n', toc);
            tic
            test_truncated(benchmark_id)
            fprintf('Time for truncated test: %.2f seconds\n', toc);
            tic
            test_permuted(benchmark_id)
            fprintf('Time for permuted test: %.2f seconds\n', toc);
            tic
            test_linearly_transformed(benchmark_id)
            fprintf('Time for linearly_transformed test: %.2f seconds\n', toc);
            tic
            test_random_nan(benchmark_id)
            fprintf('Time for random_nan test: %.2f seconds\n', toc);
            tic
            test_unrelaxable_constraints(benchmark_id)
            fprintf('Time for unrelaxable_constraints test: %.2f seconds\n', toc);
            tic
            test_nonquantifiable_constraints(benchmark_id)
            fprintf('Time for nonquantifiable_constraints test: %.2f seconds\n', toc);
            tic
            test_quantized(benchmark_id)
            fprintf('Time for quantized test: %.2f seconds\n', toc);
            tic
            test_custom(benchmark_id)
            fprintf('Time for custom test: %.2f seconds\n', toc);

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: out_${{ matrix.os }}_${{ matrix.matlab }}
          path: output/