# Check spelling

name: Check spelling

on:
  push:
  pull_request_target:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

jobs:
  spelling:
    name: Check spelling
    if: ${{ contains(github.event_name, 'pull_request') || github.event_name == 'push' }}
    permissions:
      contents: read
      pull-requests: read
      actions: read
      security-events: write
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check spelling
        id: spelling
        uses: check-spelling/check-spelling@main
        with:
          suppress_push_for_open_pull_request: ${{ github.actor != 'dependabot[bot]' && 1 }}
          checkout: true
          check_file_names: 1
          spell_check_this: check-spelling/spell-check-this@prerelease
          post_comment: 0
          use_magic_file: 1
          report-timing: 1
          warnings: bad-regex,binary-file,deprecated-feature,large-file,limited-references,no-newline-at-eof,noisy-file,non-alpha-in-dictionary,token-is-substring,unexpected-line-ending,whitespace-in-dictionary,minified-file,unsupported-configuration,no-files-to-check
          experimental_apply_changes_via_bot: 1
          use_sarif: ${{ (!github.event.pull_request || (github.event.pull_request.head.repo.full_name == github.repository)) && 1 }}
          extra_dictionary_limit: 10
          extra_dictionaries:
            cspell:html/src/html.txt
            cspell:python/src/python/python.txt
            cspell:python/src/python/python-lib.txt
            cspell:software-terms/src/software-terms.txt
            cspell:software-terms/src/software-tools.txt

  comment-push:
    name: Report (Push)
    if: ${{ (success() || failure()) && needs.spelling.outputs.followup && github.event_name == 'push' }}
    needs: spelling
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Comment
        uses: check-spelling/check-spelling@main
        with:
          checkout: true
          spell_check_this: check-spelling/spell-check-this@prerelease
          task: ${{ needs.spelling.outputs.followup }}

  comment-pr:
    name: Report (PR)
    if: ${{ (success() || failure()) && needs.spelling.outputs.followup && contains(github.event_name, 'pull_request') }}
    needs: spelling
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Comment
        uses: check-spelling/check-spelling@main
        with:
          checkout: true
          spell_check_this: check-spelling/spell-check-this@prerelease
          task: ${{ needs.spelling.outputs.followup }}
          experimental_apply_changes_via_bot: 1

  update:
    name: Update PR
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@check-spelling-bot apply') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: read
    concurrency:
      group: spelling-update-${{ github.event.issue.number }}
      cancel-in-progress: false

    steps:
      - name: Apply spelling updates
        uses: check-spelling/check-spelling@main
        with:
          experimental_apply_changes_via_bot: 1
          checkout: true
          ssh_key: "${{ secrets.CHECK_SPELLING }}"
