name: Windows summary

on:
  push:
    branches: [matlab]

jobs:

  test:

    name: MATLAB ${{ matrix.matlab }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        matlab: [latest]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB with optimization toolbox and parallel computing toolbox
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab }}
          cache: true
          products: Optimization_Toolbox Parallel_Computing_Toolbox

      - name: Setup OptiProfiler and run tests
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            root_dir = pwd()

            % Setup OptiProfiler
            setup

            % Test installation
            testOptiProfiler

            % Add './matlab/optiprofiler/tests/action_tests' to the path
            addpath(fullfile(root_dir, 'matlab/optiprofiler/tests/action_tests'))

            % Run the action tests
            test_windows

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: out_${{ matrix.os }}_${{ matrix.matlab }}
          path: ./out