name: test-matlab

on:
  push:
    branches: [matlab]

jobs:
  run:
    name: Generate coverage report for MATLAB ${{ matrix.matlab-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        matlab: [latest]
        with_optim_toolbox: [yes]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache MATLAB  # N.B.: Clear the cache when the `latest` version of MATLAB changes in March and September
        uses: actions/cache@v3.3.2
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.os }}-${{ matrix.matlab }}

      - name: Set up MATLAB with optimization toolbox
        if: ${{ matrix.with_optim_toolbox == 'yes' }}
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab }}
          products: Optimization_Toolbox Parallel_Computing_Toolbox

      - name: Setup OptiProfiler and run tests
        uses: matlab-actions/run-command@v1.2.2
        with:
          command: |
            % Run tests
            cd matlab/optiprofiler/
            runTests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./matlab/optiprofiler/coverage.xml